sample:
  description: Prometheus Client Sample
  name: prometheus_client_sample
common:
  harness: net
  min_ram: 192
  tags:
    - http
    - net
    - server
    - socket
    - prometheus
  platform_exclude:
    - native_posix
    - native_posix/native/64
  # Exclude CONFIG_HAS_RENESAS_RA_FSP as Renesas RA HAL has build error with mbedtls Socket
  filter: not CONFIG_HAS_RENESAS_RA_FSP
tests:
  sample.net.prometheus: {}
