name: Pull Zephyr

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: clone repo
      run: |
        git clone -b ${{ env.branch }} git@github.com:phytec-labs/${{ env.repository_name }}.git ${{ env.repository_name }}
      env:
        repository_name: elements-zephyr
        branch: upstream

    - name: rebase to upstream
      run: |
        cd ${{ env.repository_name }}
        git remote add upstream https://github.com/zephyrproject-rtos/zephyr.git
        git fetch upstream
        git rebase upstream/master
        cd ../
      env:
        repository_name: elements-zephyr

    - name: push back to branch
      run: |
        cd ${{ env.repository_name }}
        git push origin HEAD:${{ env.branch }} -f
        cd ../
      env:
        repository_name: elements-zephyr
        branch: upstream

    - name: post cleanup
      if: always()
      run: |
        rm -rf ${{ env.repository_name }}
      env:
        repository_name: elements-zephyr
