name: Backport Issue Check

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - v*-branch

permissions:
  contents: read

jobs:
  backport:
    name: Backport Issue Check
    concurrency:
      group: backport-issue-check-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-24.04
    if: github.repository == 'zephyrproject-rtos/zephyr'
    permissions:
      issues: read # to check if associated issue exists for backport

    steps:
      - name: Check out source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt

      - name: Install Python packages
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Run backport issue checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/release/list_backports.py \
          -o ${{ github.event.repository.owner.login }} \
          -r ${{ github.event.repository.name }} \
          -b ${{ github.event.pull_request.base.ref }} \
          -p ${{ github.event.pull_request.number }}
