name: Publish BabbleSim Tests Results

on:
  workflow_run:
    workflows: ["BabbleSim Tests"]
    types:
      - completed

permissions:
  contents: read

jobs:
  bsim-test-results:
    name: "Publish BabbleSim Test Results"
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      checks: write # to create the check run entry with test results

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@07ab29fd4a977ae4d2b275087cf67563dfdf0295 # v9
        with:
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish BabbleSim Test Results
        uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b # v2.18.0
        with:
          check_name: BabbleSim Test Results
          comment_mode: off
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: event/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "bsim-test-results/**/bsim_results.xml"
