name: Manifest
on:
  pull_request:

jobs:
  contribs:
    runs-on: ubuntu-20.04
    name: Manifest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          path: zephyrproject/zephyr
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Fix pyopenssl
        run: |
          pip install pip --upgrade
          pip install pyopenssl --upgrade

      - name: Manifest
        uses: zephyrproject-rtos/action-manifest@f54422ea250adb7cc1b9f62bfe125978bb2c58ee
        with:
          github-token: ${{ secrets.ZB_GITHUB_TOKEN }}
          manifest-path: 'west.yml'
          checkout-path: 'zephyrproject/zephyr'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest'
          dnm-labels: 'DNM'
