name: Stale Workflow Queue Cleanup

on:
  workflow_dispatch:
    branches: [main]
  schedule:
  # everyday at 15:00
  - cron: '0 15 * * *'

concurrency:
  group: stale-workflow-queue-cleanup
  cancel-in-progress: true

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-20.04

    steps:
    - name: Delete stale queued workflow runs
      uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
      with:
        repository: ${{ github.repository }}
        # Remove any workflow runs in "queued" state for more than 1 day
        older-than-seconds: 86400
        status: queued
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
