name: Merged PR stats

on:
  pull_request_target:
    branches:
      - main
      - v*-branch
    types: [closed]

permissions:
  contents: read

jobs:
  record_merged:
    if: github.event.pull_request.merged == true && github.repository == 'zephyrproject-rtos/zephyr'
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt
      - name: Install Python packages
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: PR event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELASTICSEARCH_KEY: ${{ secrets.ELASTICSEARCH_KEY }}
          ELASTICSEARCH_SERVER: "https://elasticsearch.zephyrproject.io:443"
          PR_STAT_ES_INDEX: ${{ vars.PR_STAT_ES_INDEX }}
        run: |
          python3 ./scripts/ci/stats/merged_prs.py --pull-request ${{ github.event.pull_request.number }} --repo ${{ github.repository }}
