# Copyright (c) 2024 Telink Semiconductor
# SPDX-License-Identifier: Apache-2.0

name: Telink TL721X build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-latest
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.17.0
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.xz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.xz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west blobs fetch hal_telink
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build TL721X basic/blinky
      run: |
        cd ..
        west build -b tl7218x                  -d build_blinky_tl721x                    zephyr/samples/basic/blinky                              -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721x samples/basic/button
      run: |
        cd ..
        west build -b tl7218x                  -d build_button_tl721x                    zephyr/samples/basic/button                              -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X basic/blinky_pwm
      run: |
        cd ..
        west build -b tl7218x                  -d build_blinky_pwm_tl721x                zephyr/samples/basic/blinky_pwm                          -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X hello_world
      run: |
        cd ..
        west build -b tl7218x                  -d build_hello_tl721x                     zephyr/samples/hello_world                               -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X drivers/watchdog
      run: |
        cd ..
        west build -b tl7218x                  -d build_watchdog_tl721x                  zephyr/samples/drivers/watchdog                          -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X tests/drivers/hwinfo/api
      run: |
        cd ..
        west build -b tl7218x                  -d build_hwinfo_tl721x                    zephyr/tests/drivers/hwinfo/api                          -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X sensor/sht3xd
      run: |
        cd ..
        west build -b tl7218x                  -d build_sht3xd_tl721x                    zephyr/samples/sensor/sht3xd                             -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X bluetooth/peripheral_ht
      run: |
        cd ..
        west build -b tl7218x                  -d build_peripheral_ht_tl721x             zephyr/samples/bluetooth/peripheral_ht                   -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X drivers/adc
      run: |
        cd ..
        west build -b tl7218x                  -d build_adc_tl721x                       zephyr/samples/drivers/adc/adc_dt                        -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721x samples/drivers/spi_flash
      run: |
        cd ..
        west build -b tl7218x                  -d build_spi_flash_tl721x                 zephyr/samples/drivers/spi_flash                         -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X net/openthread/cli
      run: |
        cd ..
        west build -b tl7218x                  -d build_ot_cli_tl721x                    zephyr/samples/net/openthread/cli                        -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X net/sockets/echo_server for OpenThread
      run: |
        cd ..
        west build -b tl7218x                  -d build_ot_echo_server_tl721x            zephyr/samples/net/sockets/echo_server                   -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DOVERLAY_CONFIG=overlay-ot.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build TL721X net/sockets/echo_client for OpenThread
      run: |
        cd ..
        west build -b tl7218x                  -d build_ot_echo_client_tl721x            zephyr/samples/net/sockets/echo_client                   -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build TL721X net/sockets/echo_client for OpenThread with PM deep-sleep
      run: |
        cd ..
        west build -b tl7218x_retention        -d build_ot_echo_client_pm_deep_tl721x    zephyr/samples/net/sockets/echo_client                   -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\" -DCONFIG_PM=y -DCONFIG_SOC_SERIES_RISCV_TELINK_TLX_NON_RETENTION_RAM_CODE=y

    - name: Build TL721X subsys/usb/console for USB driver
      run: |
        cd ..
        west build -b tl7218x                  -d build_usb_console_tl721x              zephyr/samples/subsys/usb/console                        -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y

    - name: Build TL721X crypto/mbedtls
      run: |
        cd ..
        west build -b tl7218x                  -d build_crypto_mbedtls_tl721x           zephyr/tests/crypto/mbedtls                              -- -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y -DCONFIG_MBEDTLS_ECP_C=y -DCONFIG_MBEDTLS_ECP_ALL_ENABLED=y

    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_tl721x/zephyr/zephyr.bin                    telink_build_artifacts/tl721x_blinky.bin
        cp ../build_blinky_pwm_tl721x/zephyr/zephyr.bin                telink_build_artifacts/tl721x_blinky_pwm.bin
        cp ../build_hello_tl721x/zephyr/zephyr.bin                     telink_build_artifacts/tl721x_hello.bin
        cp ../build_button_tl721x/zephyr/zephyr.bin                    telink_build_artifacts/tl721x_button.bin
        cp ../build_watchdog_tl721x/zephyr/zephyr.bin                  telink_build_artifacts/tl721x_watchdog.bin
        cp ../build_sht3xd_tl721x/zephyr/zephyr.bin                    telink_build_artifacts/tl721x_sht3xd.bin
        cp ../build_hwinfo_tl721x/zephyr/zephyr.bin                    telink_build_artifacts/tl721x_hwinfo.bin
        cp ../build_peripheral_ht_tl721x/zephyr/zephyr.bin             telink_build_artifacts/tl721x_peripheral_ht.bin
        cp ../build_adc_tl721x/zephyr/zephyr.bin                       telink_build_artifacts/tl721x_adc.bin
        cp ../build_usb_console_tl721x/zephyr/zephyr.bin               telink_build_artifacts/tl721x_usb_console.bin
        cp ../build_ot_cli_tl721x/zephyr/zephyr.bin                    telink_build_artifacts/tl721x_ot_cli.bin
        cp ../build_ot_echo_server_tl721x/zephyr/zephyr.bin            telink_build_artifacts/tl721x_ot_echo_server.bin
        cp ../build_ot_echo_client_tl721x/zephyr/zephyr.bin            telink_build_artifacts/tl721x_ot_echo_client.bin
        cp ../build_ot_echo_client_pm_deep_tl721x/zephyr/zephyr.bin    telink_build_artifacts/tl721x_ot_echo_client_pm_retention.bin
        cp ../build_crypto_mbedtls_tl721x/zephyr/zephyr.bin            telink_build_artifacts/tl721x_mbedtls.bin
        cp ../build_spi_flash_tl721x/zephyr/zephyr.bin                 telink_build_artifacts/tl721x_spi_flash.bin

    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          telink_build_artifacts/*
