name: Telink TL321x build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-20.04
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.15.2
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west blobs fetch hal_telink
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build TL321x basic/blinky
      run: |
        cd ..
        west build -b tl3218x                  -d build_blinky_tl321x                 zephyr/samples/basic/blinky

    - name: Build TL321x hello_world
      run: |
        cd ..
        west build -b tl3218x                  -d build_hello_tl321x                  zephyr/samples/hello_world

    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_tl321x/zephyr/zephyr.bin telink_build_artifacts/tl321x_blinky.bin

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          telink_build_artifacts/*
