name: Telink W91 build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-20.04
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.15.2
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build W91 basic/blinky
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_blinky_w91                    zephyr/samples/basic/blinky

    - name: Build W91 basic/button
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_button_w91                    zephyr/samples/basic/button

    - name: Build W91 I2C sensor/mpu6050
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_mpu6050_w91                   zephyr/samples/sensor/mpu6050

    - name: Build W91 subsys/nvs
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_nvs_w91                       zephyr/samples/subsys/nvs

    - name: Build W91 bootloader/mcuboot/boot
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_mcuboot_w91                   bootloader/mcuboot/boot/zephyr                           -- -DCONFIG_LOG_DEFAULT_LEVEL=3

    - name: Build W91 basic/blinky for DFU
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_blinky_dfu_w91                zephyr/samples/basic/blinky                              -- -DCONFIG_BOOTLOADER_MCUBOOT=y

    - name: Build W91 bluetooth/peripheral_ht
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_bt_peripheral_ht_w91          zephyr/samples/bluetooth/peripheral_ht

    - name: Build W91 sock_simple IPv4
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_sock_simple_ipv4_w91          zephyr/samples/boards/tlsr9x/sock_simple

    - name: Build W91 sock_simple IPv6
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_sock_simple_ipv6_w91          zephyr/samples/boards/tlsr9x/sock_simple                 -- -DCONFIG_APP_SOCKET_UDP_IPV6=y

    - name: Build W91 key_matrix
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_key_matrix                    zephyr/samples/boards/tlsr9x/key_matrix

    - name: Build W91 key_pool
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_key_pool                      zephyr/samples/boards/tlsr9x/key_pool

    - name: Build W91 led_pool
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_led_pool                      zephyr/samples/boards/tlsr9x/led_pool/

    - name: Build W91 pwm_pool
      run: |
        cd ..
        west build -b tlsr9118bdk40d             -d build_pwm_pool                      zephyr/samples/boards/tlsr9x/pwm_pool/


    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_w91/zephyr/zephyr.bin                    telink_build_artifacts/w91_blinky.bin
        cp ../build_button_w91/zephyr/zephyr.bin                    telink_build_artifacts/w91_button.bin
        cp ../build_mpu6050_w91/zephyr/zephyr.bin                   telink_build_artifacts/w91_mpu6050.bin
        cp ../build_nvs_w91/zephyr/zephyr.bin                       telink_build_artifacts/w91_nvs.bin
        cp ../build_mcuboot_w91/zephyr/zephyr.bin                   telink_build_artifacts/w91_mcuboot.bin
        cp ../build_blinky_dfu_w91/zephyr/zephyr.signed.bin         telink_build_artifacts/w91_blinky_dfu.signed.bin
        cp ../build_bt_peripheral_ht_w91/zephyr/zephyr.bin          telink_build_artifacts/w91_bt_peripheral_ht.bin
        cp ../build_sock_simple_ipv4_w91/zephyr/zephyr.bin          telink_build_artifacts/w91_wifi_socket_udp_ipv4.bin
        cp ../build_sock_simple_ipv6_w91/zephyr/zephyr.bin          telink_build_artifacts/w91_wifi_socket_udp_ipv6.bin
        cp ../build_key_matrix/zephyr/zephyr.bin                    telink_build_artifacts/w91_key_matrix.bin
        cp ../build_key_pool/zephyr/zephyr.bin                      telink_build_artifacts/w91_key_pool.bin
        cp ../build_led_pool/zephyr/zephyr.bin                      telink_build_artifacts/w91_led_pool.bin
        cp ../build_pwm_pool/zephyr/zephyr.bin                      telink_build_artifacts/w91_pwm_pool.bin

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          telink_build_artifacts/*
