name: Telink B95 build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-20.04
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.15.2
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west blobs fetch hal_telink
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build B95 basic/blinky
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_blinky_b95                    zephyr/samples/basic/blinky

    - name: Build B95 basic/blinky_pwm
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_blinky_pwm_b95                zephyr/samples/basic/blinky_pwm

    - name: Build B95 hello_world
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_hello_b95                     zephyr/samples/hello_world

    - name: Build B95 drivers/watchdog
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_watchdog_b95                  zephyr/samples/drivers/watchdog

    - name: Build B95 sensor/sht3xd
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_sht3xd_b95                    zephyr/samples/sensor/sht3xd

    - name: Build B95 bluetooth/peripheral_ht
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_peripheral_ht_b95             zephyr/samples/bluetooth/peripheral_ht

    - name: Build B95 net/openthread/cli
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_ot_cli_b95                    zephyr/samples/net/openthread/cli                        -- -DOVERLAY_CONFIG=overlay-telink-fixed-mac.conf

    - name: Build B95 net/openthread/coprocessor in RCP configuration with UART interface
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_ot_coprocessor_rcp_uart_b95   zephyr/samples/net/openthread/coprocessor                -- -DOVERLAY_CONFIG=overlay-rcp.conf

    - name: Build B95 net/sockets/echo_server for OpenThread
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_ot_echo_server_b95            zephyr/samples/net/sockets/echo_server                   -- -DOVERLAY_CONFIG=overlay-ot.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build B95 net/sockets/echo_client for OpenThread
      run: |
        cd ..
        west build -b tlsr9258a                  -d build_ot_echo_client_b95            zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build B95 subsys/usb/console for USB driver
      run: |
        cd ..
        west build -b tlsr9258a             -d build_usb_console_b95               zephyr/samples/subsys/usb/console

    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_b95/zephyr/zephyr.bin                    telink_build_artifacts/b95_blinky.bin
        cp ../build_blinky_pwm_b95/zephyr/zephyr.bin                telink_build_artifacts/b95_blinky_pwm.bin
        cp ../build_hello_b95/zephyr/zephyr.bin                     telink_build_artifacts/b95_hello.bin
        cp ../build_watchdog_b95/zephyr/zephyr.bin                  telink_build_artifacts/b95_watchdog.bin
        cp ../build_sht3xd_b95/zephyr/zephyr.bin                    telink_build_artifacts/b95_sht3xd.bin
        cp ../build_peripheral_ht_b95/zephyr/zephyr.bin             telink_build_artifacts/b95_peripheral_ht.bin
        cp ../build_ot_cli_b95/zephyr/zephyr.bin                    telink_build_artifacts/b95_ot_cli.bin
        cp ../build_ot_coprocessor_rcp_uart_b95/zephyr/zephyr.bin   telink_build_artifacts/b95_ot_coprocessor_rcp_uart.bin
        cp ../build_ot_echo_server_b95/zephyr/zephyr.bin            telink_build_artifacts/b95_ot_echo_server.bin
        cp ../build_ot_echo_client_b95/zephyr/zephyr.bin            telink_build_artifacts/b95_ot_echo_client.bin
        cp ../build_usb_console_b95/zephyr/zephyr.bin               telink_build_artifacts/b95_usb_console.bin
        cp ../modules/hal/telink/zephyr/blobs/liblt_9258_zephyr.a   telink_build_artifacts/liblt_9258_zephyr.a

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          telink_build_artifacts/*
