name: Telink build examples

on: pull_request

jobs:
  telink_build_examples:
    runs-on: ubuntu-20.04
    name: Telink build examples
    env:
      ZEPHYR_SDK_VERSION: 0.15.2
    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libdigest-sha-perl cmake python3 ninja-build

    - name: Setup Zephyr toolchain
      run: |
        mkdir ~/zephyr_sdk
        wget -q -P ~/zephyr_sdk https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz
        (cd ~/zephyr_sdk && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v"${ZEPHYR_SDK_VERSION}"/sha256.sum | shasum --check --ignore-missing)
        tar xf ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}"_linux-x86_64.tar.gz -C ~/zephyr_sdk
        (cd ~/zephyr_sdk/zephyr-sdk-"${ZEPHYR_SDK_VERSION}" && ./setup.sh -t riscv64-zephyr-elf -c)

    - name: Checkout Zephyr
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: West setup
      run: |
        pip install west
        cd ..
        west init -l zephyr
        west update
        west blobs fetch hal_telink
        west zephyr-export
        pip install -r zephyr/scripts/requirements.txt

    - name: Build B91 basic/blinky
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_blinky_b91                    zephyr/samples/basic/blinky

    - name: Build B92 basic/blinky
      run: |
        cd ..
        west build -b tlsr9528a                  -d build_blinky_b92                    zephyr/samples/basic/blinky

    - name: Build basic/blinky with PM
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_blinky_pm                     zephyr/samples/basic/blinky                              -- -DCONFIG_PM=y

    - name: Build bluetooth/peripheral_ht
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_bt_peripheral_ht              zephyr/samples/bluetooth/peripheral_ht

    - name: Build bluetooth/peripheral_ht with PM
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_bt_peripheral_ht_pm           zephyr/samples/bluetooth/peripheral_ht                   -- -DCONFIG_PM=y

    - name: Build net/openthread/coprocessor in RCP configuration with UART interface for B91
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_ot_coprocessor_rcp_uart_b91   zephyr/samples/net/openthread/coprocessor                -- -DOVERLAY_CONFIG=overlay-rcp.conf

    - name: Build net/openthread/coprocessor in RCP configuration with UART interface for B92
      run: |
        cd ..
        west build -b tlsr9528a                  -d build_ot_coprocessor_rcp_uart_b92   zephyr/samples/net/openthread/coprocessor                -- -DOVERLAY_CONFIG=overlay-rcp.conf

    - name: Build net/sockets/echo_server for OpenThread for B91
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_ot_echo_server_b91            zephyr/samples/net/sockets/echo_server                   -- -DOVERLAY_CONFIG=overlay-ot.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build net/sockets/echo_server for OpenThread for B92
      run: |
        cd ..
        west build -b tlsr9528a                  -d build_ot_echo_server_b92            zephyr/samples/net/sockets/echo_server                   -- -DOVERLAY_CONFIG=overlay-ot.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build net/sockets/echo_client for OpenThread for B91
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_ot_echo_client_b91            zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"

    - name: Build net/sockets/echo_client for OpenThread for B92
      run: |
        cd ..
        west build -b tlsr9528a                  -d build_ot_echo_client_b92            zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\"


    - name: Build net/sockets/echo_client for OpenThread with PM for B91
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_ot_echo_client_pm_b91         zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\" -DCONFIG_PM=y

    - name: Build net/sockets/echo_client for OpenThread with PM for B92
      run: |
        cd ..
        west build -b tlsr9528a                  -d build_ot_echo_client_pm_b92         zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\" -DCONFIG_PM=y

    - name: Build bootloader/mcuboot/boot for B91
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_mcuboot_b91                   bootloader/mcuboot/boot/zephyr                           -- -DCONFIG_LOG_DEFAULT_LEVEL=4

    - name: Build bootloader/mcuboot/boot for B92
      run: |
        cd ..
        west build -b tlsr9528a                  -d build_mcuboot_b92                   bootloader/mcuboot/boot/zephyr                           -- -DCONFIG_LOG_DEFAULT_LEVEL=4 -DCONFIG_BOOT_MAX_IMG_SECTORS=4096


    - name: Build subsys/mgmt/mcumgr/smp_svr for Bluetooth
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_bt_smp_svr                    zephyr/samples/subsys/mgmt/mcumgr/smp_svr                -- -DOVERLAY_CONFIG=overlay-bt.conf

    - name: Build subsys/usb/console for USB driver
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_usb_console                   zephyr/samples/subsys/usb/console

    - name: Build net/openthread/coprocessor in RCP configuration with USB interface
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_ot_coprocessor_rcp_usb        zephyr/samples/net/openthread/coprocessor                -- -DDTC_OVERLAY_FILE="usb.overlay boards/tlsr9518adk80d-dongle.overlay" -DOVERLAY_CONFIG=overlay-rcp-usb-telink.conf

    - name: Build zephyr/samples/boards/tlsr9518adk80d_retention/basic
      run: |
        cd ..
        west build -b tlsr9518adk80d_retention   -d build_retention_basic               zephyr/samples/boards/tlsr9518adk80d_retention/basic     -- -DCONFIG_BOARD_TLSR9518ADK80D_NON_RETENTION_RAM_CODE=y

    - name: Build net/sockets/echo_client for OpenThread with PM deep-sleep
      run: |
        cd ..
        west build -b tlsr9518adk80d_retention   -d build_ot_echo_client_pm_deep    zephyr/samples/net/sockets/echo_client                   -- -DOVERLAY_CONFIG=overlay-ot-sed.conf -DCONFIG_OPENTHREAD_NETWORKKEY=\"09:24:01:56:04:4a:45:0b:23:22:1e:0e:3b:0d:0e:61:2f:1b:2c:24\" -DCONFIG_PM=y -DCONFIG_BOARD_TLSR9518ADK80D_NON_RETENTION_RAM_CODE=y -DCONFIG_TELINK_B91_2_WIRE_SPI_ENABLE=y

    - name: Build bootloader/mcuboot/boot for USB DFU
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_mcuboot_usb_dfu           bootloader/mcuboot/boot/zephyr                           -- -DCONFIG_LOG_DEFAULT_LEVEL=3 -DCONFIG_USB_DFU_WILL_DETACH=n -DCONFIG_BOOT_USB_DFU_GPIO=y -DCONFIG_MCUBOOT_INDICATION_LED=y

    - name: Build basic/blinky for USB DFU
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_blinky_usb_dfu            zephyr/samples/basic/blinky                              -- -DCONFIG_BOOTLOADER_MCUBOOT=y

    - name: net/openthread/cli
      run: |
        cd ..
        west build -b tlsr9518adk80d             -d build_ot_cli                    zephyr/samples/net/openthread/cli                        -- -DOVERLAY_CONFIG=overlay-telink-features.conf

    - name: Collect artifacts
      run: |
        mkdir telink_build_artifacts
        cp ../build_blinky_b91/zephyr/zephyr.bin                    telink_build_artifacts/b91_blinky.bin
        cp ../build_blinky_b92/zephyr/zephyr.bin                    telink_build_artifacts/b92_blinky.bin
        cp ../build_blinky_pm/zephyr/zephyr.bin                     telink_build_artifacts/blinky_pm.bin
        cp ../build_bt_peripheral_ht/zephyr/zephyr.bin              telink_build_artifacts/bt_peripheral_ht.bin
        cp ../build_bt_peripheral_ht_pm/zephyr/zephyr.bin           telink_build_artifacts/bt_peripheral_ht_pm.bin
        cp ../build_ot_coprocessor_rcp_uart_b91/zephyr/zephyr.bin   telink_build_artifacts/b91_ot_coprocessor_rcp_uart.bin
        cp ../build_ot_coprocessor_rcp_uart_b92/zephyr/zephyr.bin   telink_build_artifacts/b92_ot_coprocessor_rcp_uart.bin
        cp ../build_ot_echo_server_b91/zephyr/zephyr.bin            telink_build_artifacts/b91_ot_echo_server.bin
        cp ../build_ot_echo_server_b92/zephyr/zephyr.bin            telink_build_artifacts/b92_ot_echo_server.bin
        cp ../build_ot_echo_client_b91/zephyr/zephyr.bin            telink_build_artifacts/b91_ot_echo_client.bin
        cp ../build_ot_echo_client_b92/zephyr/zephyr.bin            telink_build_artifacts/b92_ot_echo_client.bin
        cp ../build_ot_echo_client_pm_b91/zephyr/zephyr.bin         telink_build_artifacts/b91_ot_echo_client_pm.bin
        cp ../build_ot_echo_client_pm_b92/zephyr/zephyr.bin         telink_build_artifacts/b92_ot_echo_client_pm.bin
        cp ../build_mcuboot_b91/zephyr/zephyr.bin                   telink_build_artifacts/b91_mcuboot.bin
        cp ../build_mcuboot_b92/zephyr/zephyr.bin                   telink_build_artifacts/b92_mcuboot.bin
        cp ../build_bt_smp_svr/zephyr/zephyr.signed.bin             telink_build_artifacts/bt_smp_svr.signed.bin
        cp ../build_usb_console/zephyr/zephyr.bin                   telink_build_artifacts/usb_console.bin
        cp ../build_ot_coprocessor_rcp_usb/zephyr/zephyr.bin        telink_build_artifacts/ot_coprocessor_rcp_usb.bin
        cp ../build_retention_basic/zephyr/zephyr.bin               telink_build_artifacts/retention_basic.bin
        cp ../build_ot_echo_client_pm_deep/zephyr/zephyr.bin        telink_build_artifacts/ot_echo_client_pm_retention.bin
        cp ../build_mcuboot_usb_dfu/zephyr/zephyr.bin               telink_build_artifacts/mcuboot_usb_dfu.bin
        cp ../build_blinky_usb_dfu/zephyr/zephyr.signed.bin         telink_build_artifacts/blinky_usb_dfu.signed.bin
        cp ../build_ot_cli/zephyr/zephyr.bin                        telink_build_artifacts/ot_cli.bin

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          telink_build_artifacts/*
