name: Publish Twister Test Results

on:
  workflow_run:
    workflows: ["Run tests with twister"]
    branches:
      - main
    types:
      - completed

permissions:
  contents: read

jobs:
  upload-to-elasticsearch:
    if: |
      github.repository == 'zephyrproject-rtos/zephyr' &&
      github.event.workflow_run.event != 'pull_request'
    env:
      ELASTICSEARCH_KEY: ${{ secrets.ELASTICSEARCH_KEY }}
      ELASTICSEARCH_SERVER: "https://elasticsearch.zephyrproject.io:443"
    runs-on: ubuntu-24.04
    steps:
      # Needed for elasticearch and upload script
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt
      - name: Install Python packages
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Download Artifacts
        id: download-artifacts
        uses: dawidd6/action-download-artifact@0bd50d53a6d7fb5cb921e607957e9cc12b4ce392 # v12
        with:
          path: artifacts
          workflow: twister.yml
          run_id: ${{ github.event.workflow_run.id }}
          if_no_artifact_found: ignore

      - name: Upload to elasticsearch
        if: steps.download-artifacts.outputs.found_artifact == 'true'
        run: |
          # set run date on upload to get consistent and unified data across the matrix.
          run_date=`date --iso-8601=minutes`
          if [ "${{github.event.workflow_run.event}}" = "push" ]; then
            python3 ./scripts/ci/upload_test_results_es.py -r ${run_date} \
            --run-attempt ${{github.run_attempt}} \
            --run-branch ${{github.ref_name}} \
            --index zephyr-main-ci-push-1 artifacts/*/*/twister.json
          elif [ "${{github.event.workflow_run.event}}" = "schedule" ]; then
            python3 ./scripts/ci/upload_test_results_es.py -r ${run_date} \
            --run-attempt ${{github.run_attempt}} \
            --run-branch ${{github.ref_name}} \
            --index zephyr-main-ci-weekly-1 artifacts/*/*/twister.json
          fi
